### ISSUE TITLE
BDtW-NumberedBracketedCite* templates broken

### ISSUE THREAD

**Issue by aglatz** [ackman678/bibdesktoword#1]
Hi,
I just cloned the recent git version of bibdesktoword and tried to generate citations with the BDtW-NumberedBracketedCite\* scheme. However, the BibDeskToWord.py python script didn't replace the generated citations from BibDesk and I ended up with in text citations that always started with [1, ...].

After a bit of investigation, I found out that the BDtW-NumberedBracketedCite\* were broken. After fixing them by insterting :::Index:<$itemIndex/>::: instead of just <$itemIndex/> I got the proper reference numbers in my text after running the script.

Other than that BibdeskToWork works like a charm with Bibdesk 1.5.10 and Word 2011 on OSX10.5.8.

Best,

A.

**Comment by ackman678** [comment]
Excellent, thanks!
